parameters:
    database_driver: pdo_mysql
    database_host: 192.168.1.99
    database_port: null
    database_name: SigueDB
    database_user: webapp
    database_password: webapppass
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 77761916694be730c54ce4cb8015a5c0cee7e654
    database_path: null
