si_sigue_homepage:
    pattern:  /inicio
    defaults: { _controller: SISigueBundle:Default:index }
si_sigue_login:
    pattern:  /login
    defaults: { _controller: SISigueBundle:Default:login }
si_sigue_perfil_alumno:
    pattern:  /Alumno/inicio
    defaults:   {_controller: SISigueBundle:Alumno:index}
si_sigue_perfil_profesor:
    pattern:  /Profesor/inicio/{exito}
    defaults:   {_controller: SISigueBundle:Profesor:index, exito:true}
    requirements:
        culture:  true|false
si_sigue_subir_profesor:
    pattern:  /Profesor/subir_alumno
    defaults:   {_controller: SISigueBundle:Profesor:subir_alumno}
