si_sigue_homepage:
    pattern:  /inicio/{error}
    defaults: { _controller: SISigueBundle:Default:index, error:"" }
si_sigue_login:
    pattern:  /login/{error}
    defaults: { _controller: SISigueBundle:Default:login, error:"" }
si_sigue_admin:
    pattern:  /admin
    defaults: { _controller: SISigueBundle:Default:admin }
si_sigue_recuperar:
    pattern:  /recuperar/{exito}
    defaults: { _controller: SISigueBundle:Default:recuperar, exito:"" }
si_sigue_recuperar_guardar:
    pattern:  /recuperarg/{exito}
    defaults: { _controller: SISigueBundle:Default:recuperar_guardar, exito:"" }
si_sigue_add_profesor:
    pattern:  /add_profesor
    defaults: { _controller: SISigueBundle:Default:add_profesor }
si_sigue_logout:
    pattern:  /logout
    defaults: { _controller: SISigueBundle:Default:logout }
si_sigue_perfil_alumno:
    pattern:  /Alumno/inicio
    defaults:   {_controller: SISigueBundle:Alumno:perfil }
si_sigue_perfil_editar:
    pattern:  /Alumno/inicio/editar
    defaults:   {_controller: SISigueBundle:Alumno:cambiarPassword }
    methods:  [POST]
si_sigue_perfil_correoAdicional:
    pattern:  /Alumno/inicio/correoAdicional
    defaults:   {_controller: SISigueBundle:Alumno:correoAdicional }
    methods:  [POST]
si_sigue_alumno_token:
    pattern:  /Alumno/registrar/{asig}
    defaults:   {_controller: SISigueBundle:Alumno:token }
    methods:  [POST]
si_sigue_activar_app:
    pattern:  /Profesor/activar_app
    defaults: { _controller: SISigueBundle:Profesor:activar_app }    
si_sigue_perfil_profesor:
    pattern:  /Profesor/inicio/{exito}
    defaults:   {_controller: SISigueBundle:Profesor:index, exito:none}
    requirements:       
si_sigue_subir_profesor:
    pattern:  /Profesor/subir_alumno
    defaults:   {_controller: SISigueBundle:Profesor:subir_alumno}
si_sigue_generar_tokens:
    pattern:  /Profesor/generar_tokens/{id_asignatura}
    defaults:   {_controller: SISigueBundle:Profesor:generar_tokens}
si_sigue_metodo_evaluacion:
    pattern:  /Profesor/metodo/{id_asignatura}
    defaults:   {_controller: SISigueBundle:Profesor:metodo}
si_sigue_generar_tokens_profesor:
    pattern:  /Profesor/generar_qr
    defaults:   {_controller: SISigueBundle:Profesor:generar_qr}
si_sigue_alumno_activar_app:
    pattern:  /Alumno/activar_app
    defaults: { _controller: SISigueBundle:Alumno:activarApp } 
si_sigue_alumno_estadisticas:
    pattern:  /Alumno/estadisticas/{asig}
    defaults:   {_controller: SISigueBundle:Alumno:estadisticas }
si_sigue_descargar_pdf_profesor:
    pattern:  /Profesor/descargar_pdf/{pdf}
    defaults:   {_controller: SISigueBundle:Profesor:descargar_pdf}
si_sigue_estadisticas_asignatura_profesor:
    pattern:  /Profesor/estadisticas/{id_asignatura}
    defaults:   {_controller: SISigueBundle:Profesor:stats}
si_sigue_calificar_profesor:
    pattern:  /Profesor/calificar/{id_asignatura}
    defaults:   {_controller: SISigueBundle:Profesor:calificar}  
si_sigue_calificar_actividad_profesor:
    pattern:  /Profesor/calificar/{id_asignatura}/{id_alumno}
    defaults:   {_controller: SISigueBundle:Profesor:calificar_actividad}  
si_sigue_calificar_actividad_guardar:
    pattern:  /Profesor/calificar/{id_asignatura}/{id_alumno}/ok
    defaults:   {_controller: SISigueBundle:Profesor:calificar_actividad_guardar}  
si_sigue_guardar_calificaciones:
    pattern:  /Profesor/guardar_calificaciones/{id_asignatura}
    defaults:   {_controller: SISigueBundle:Profesor:guardar_calificaciones}   
si_sigue_exportar_calificaciones:
    pattern:  /Profesor/exportar_calificaciones/{id_asignatura}
    defaults:   {_controller: SISigueBundle:Profesor:exportar_calificaciones} 
si_sigue_importar_calificaciones:
    pattern:  /Profesor/importar_calificaciones
    defaults:   {_controller: SISigueBundle:Profesor:importar_calificaciones} 
si_sigue_generar_actividad_profesor:
    pattern:  /Profesor/generar_actividad
    defaults:   {_controller: SISigueBundle:Profesor:generar_actividad}   
si_sigue_cambiar_metodo_evaluacion:
    pattern:  /Profesor/cambiar_metodo
    defaults:   {_controller: SISigueBundle:Profesor:cambiar_metodo}   
si_sigue_notificar_calificaciones:
    pattern:  /Profesor/notificar/{id_asignatura}
    defaults:   {_controller: SISigueBundle:Profesor:notificar}   
si_sigue_add_profesor_asignatura:
    pattern:  /Profesor/add_profesor_asignatura/{exito}
    defaults:   {_controller: SISigueBundle:Profesor:add_profesor_asignatura}   
si_sigue_add_profesor_asignatura_guardar:
    pattern:  /Profesor/add_profesor_asignatura_guardar
    defaults:   {_controller: SISigueBundle:Profesor:add_profesor_asignatura_guardar}   
si_sigue_add_asignatura:
    pattern:  /Profesor/add_asignatura
    defaults:   {_controller: SISigueBundle:Profesor:add_asignatura} 
si_sigue_cambiar_password:
    pattern:  /Profesor/cambiar_password
    defaults:   {_controller: SISigueBundle:Profesor:cambiar_password} 
si_sigue_cambiar_password_guardar:
    pattern:  /Profesor/cambiar_password_guardar
    defaults:   {_controller: SISigueBundle:Profesor:cambiar_passwordGuardar}
si_sigue_add_alumno:
    pattern:  /Profesor/add_alumno/{id_asignatura}
    defaults:   {_controller: SISigueBundle:Profesor:add_alumno} 
si_sigue_add_alumno_guardar:
    pattern:  /Profesor/add_alumno_guardar/{id_asignatura}
    defaults:   {_controller: SISigueBundle:Profesor:add_alumnoGuardar}     
    
    