si_sigue_homepage:
    pattern:  /inicio
    defaults: { _controller: SISigueBundle:Default:index }
si_sigue_login:
    pattern:  /login
    defaults: { _controller: SISigueBundle:Default:login }
si_sigue_perfil_alumno:
    pattern:  /Alumno/inicio
    defaults:   {_controller: SISigueBundle:Alumno:perfil }
si_sigue_alumno_registrar:
    pattern:  /Alumno/registrar/{id}/{asig}
    defaults:   {_controller: SISigueBundle:Alumno:registrar }
    methods:  [GET]
si_sigue_alumno_token:
    pattern:  /Alumno/registrar/{id}/{asig}
    defaults:   {_controller: SISigueBundle:Alumno:token }
    methods:  [POST]
si_sigue_perfil_profesor:
    pattern:  /Profesor/inicio/{exito}
    defaults:   {_controller: SISigueBundle:Profesor:index, exito:none}
    requirements:       
si_sigue_subir_profesor:
    pattern:  /Profesor/subir_alumno
    defaults:   {_controller: SISigueBundle:Profesor:subir_alumno}
si_sigue_generar_tokens_profesor:
    pattern:  /Profesor/generar_qr
    defaults:   {_controller: SISigueBundle:Profesor:generar_qr}
si_sigue_alumno_estadisticas:
    pattern:  /Alumno/estadisticas/{id}/{asig}
    defaults:   {_controller: SISigueBundle:Alumno:estadisticas }
