parameters:
#    si_sigue.example.class: SI\SigueBundle\Example

services:
#    si_sigue.example:
#        class: %si_sigue.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
